; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "teamwork2magento"
#define MyAppVersion "2.0"
#define MyAppPublisher "Robert E. Tuttle III"
#define MyAppURL "n/a"
#define MyAppExeName "teamwork2magento.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5DD48403-2BCB-4745-9CCB-6F57574194F0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
LicenseFile=C:\Users\King Tuts\Desktop\t2m_archive\lpgl license document\GNU_LPGL_V3.rtf
InfoBeforeFile=C:\Users\King Tuts\Desktop\t2m_archive\teamwork2magento_1.0\setup scripts\before_install_preview.rtf
InfoAfterFile=C:\Users\King Tuts\Desktop\t2m_archive\teamwork2magento_1.0\setup scripts\after_install_preview.rtf
OutputDir=setup_teamwork2magento
OutputBaseFilename=t2m_ver2_setup
Password=!QW#4rt6
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\teamwork2magento.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\D3Dcompiler_47.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\export_obj.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\libEGL.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\libgcc_s_dw2-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\libGLESV2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\main.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\mainwindow.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\moc_mainwindow.cpp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\moc_mainwindow.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\moc_preview.cpp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\moc_preview.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\preview.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\qrc_resources.cpp"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\qrc_resources.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\Qt5Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\Qt5Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\Qt5Svg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\Qt5Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\teamwork2magento_resource_res.o"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\iconengines\qsvgicon.dll"; DestDir: "{app}\iconengines"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\imageformats\qdds.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\imageformats\qgif.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\imageformats\qicns.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\imageformats\qico.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\imageformats\qjp2.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\imageformats\qjpeg.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\imageformats\qmng.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\imageformats\qsvg.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\imageformats\qtga.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\imageformats\qtiff.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\imageformats\qwbmp.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\imageformats\qwebp.dll"; DestDir: "{app}\imageformats"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\platforms\qwindows.dll"; DestDir: "{app}\platforms"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\translations\qt_ca.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\translations\qt_cs.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\translations\qt_de.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\translations\qt_fi.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\translations\qt_fr.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\translations\qt_hu.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\translations\qt_it.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\translations\qt_ja.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\translations\qt_ko.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\translations\qt_lv.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\translations\qt_ru.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\translations\qt_sk.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\build-teamwork2magento-Desktop_Qt_5_5_0_MinGW_32bit-Release\release\translations\qt_uk.qm"; DestDir: "{app}\translations"; Flags: ignoreversion
Source: "C:\Users\King Tuts\Documents\teamwork2magento_archive\teamwork2magento_2.0\teamwork2magento\images\appicon.ico"; DestDir: "{app}\images"; Flags: ignoreversion
Source: "C:\Users\King Tuts\Documents\teamwork2magento_archive\teamwork2magento_2.0\teamwork2magento\images\bmp_icon4exe.bmp"; DestDir: "{app}\images"; Flags: ignoreversion
Source: "C:\Users\King Tuts\Documents\teamwork2magento_archive\teamwork2magento_2.0\teamwork2magento\images\dialog_icon.bmp"; DestDir: "{app}\images"; Flags: ignoreversion
Source: "C:\Users\King Tuts\Documents\teamwork2magento_archive\teamwork2magento_2.0\teamwork2magento\images\icon4exe.ico"; DestDir: "{app}\images"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

